[workspace]
members = [
    "lib/dexes",
    "lib/chains",
    "lib/sol",
    "lib/v3",
    "server",
]
resolver = "3"

[workspace.dependencies]
alloy = "1.0.31"
alloy-contract = "1.0.27"
alloy-rpc-types = "1.0.31"
alloy-sol-types = "1.3.1"
alloy-primitives = "1.3.1"
alloy-provider = "1.0.31"

serde = {version = "1.0.223", features = ["derive"]}
serde_json = "1.0.23"
