[package]
name = "arbitro"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2"
num-bigint = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
axum = "0.6"
ethers = { version = "2.0", features = ["abigen","ws","rustls"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
bigdecimal = "0.4.7"
rust_decimal = { version = "1.36", features = ["maths"] }
rust_decimal_macros = "1.36"
futures = "0.3.31"
rayon = "1.10.0"
crossbeam-channel = "0.5.15"
thiserror = "2.0.12"
ethers-providers = "2.0.14"
clap = "4.5.37"
async-trait = "0.1.88"
tokio-stream = "0.1.17"
anyhow = "1.0.98"

