[package]
name = "arbitro"
version = "0.1.0"
edition = "2021"

[dependencies]
graph = { path = "/home/pedro/graph" }
num-traits = "0.2"
num-bigint = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
axum = "0.6"
ethers = { version = "2.0", features = ["abigen","ws"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
bigdecimal = "0.4.7"
rust_decimal = { version = "1.36", features = ["maths"] }
rust_decimal_macros = "1.36"
futures = "0.3.31"
rayon = "1.10.0"
crossbeam-channel = "0.5.15"

